# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 150189a30c2be14d5d0ff73797f14fd10b78c2ed24a9cc7b2dc938e7b62d8e54e86df3f3e1ab01b37c2a7f5c7896219bfa3e0029e70116e8a74e58929a583d9f

test:
  secret_key_base: 0af3d4a3c490d77c9641507cd77f4ae639ccaf3a9538ea51ed878fd23e2883794e4187c8767a322112701d3a226256e59bfb8e778f6b0eb6291bd332d6d145de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
